request = Paypal::Express::Request.new(
  :username   => pwz2k-facilitator_api1.hotmail.com,
  :password   => 1384963232,
  :signature  => An5ns1Kso7MWUdW4ErQKJJJ4qi4-Asss8sIUzSk7XExg2DcSoBaM5nXe
)
payment_request = Paypal::Payment::Request.new(
  :currency_code => :USD, # if nil, PayPal use USD as default
  :amount        => 60,
  :items => [{
    :name => 1 MONTH OF SUBSCRIPTION,
    :description => PAY FOR ACCESS TO SITE,
    :amount => 120,
    :category => :Digital
  }]
)
response = request.setup(
  payment_request,
  YOUR_SUCCESS_CALBACK_URL,
  YOUR_CANCEL_CALBACK_URL,
  :no_shipping => true
)
response.popup_uri